# Generated by Django 2.2.7 on 2019-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(
                default='none', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
